version: '3.7'

services:
  rabbitmq3:
    container_name: "rabbitmq"
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'

  user-svc:
    image: "user-svc"
    build:
      context: .
      dockerfile: ./ops/Dockerfile
    container_name: "user-svc"
    ports:
      - "8080:80"
    volumes:
      - ".:/app/service"
    networks:
      - user-svc-net

  user-svc-db:
    image: "postgres:latest"
    container_name: user-svc-db
    volumes:
      - user-svc-db-volume:/var/lib/postgresql/data
    ports:
      - "8085:5432"
    env_file:
      - "./ops/service.env"
    networks:
      - user-svc-net

volumes:
  user-svc-db-volume:
    name: user-svc-db-volume
    driver: local

networks:
  user-svc-net:
    name: user-svc-net
    driver: bridge